blogging/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import *


app_name = "core"

urlpatterns = [
    path('', homepage, name="homepage"),
    path('signup/', register_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='reset_password'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # posts
    path('post/create/', post_create_view, name='post_create'),
    path('post/<slug:slug>/edit/', post_edit, name='post_edit'),
    path('post/<slug:slug>/delete/', post_delete, name='post_delete'),
    path('post/<slug:slug>/', post_detail, name='post_detail'),
    path('category/<str:category_slug>/', category_posts, name='category-posts'),
    path('tag/<str:tag_slug>/', tag_posts, name='tag-posts'),

    #user
    path('user/@<str:username>/', profile_view, name='profile'),
    path('user/@<str:username>/edit/', settings, name='settings'),
    path('search/', search, name='search'),

]

templates/snippets/comments.html
<div class="pt-5">
  <h3 class="mb-5">{{ comments.count }} Comments</h3>
  <ul class="comment-list">
    {% for comment in comments %}
      {% if comment.is_parent %}
        <li class="comment">
          <!-- Display parent comment -->
          <div class="vcard">
            <img src="{{ comment.author.profile_picture.url }}" alt="Image placeholder">
          </div>
          <div class="comment-body">
            <h3>
              <a href="{% url 'core:profile' comment.author.user.username %}">
                {{ comment.author.user.username|title }}
              </a>
              <span class="small meta">- {{ comment.created_at }}</span>
            </h3>
            <p>{{ comment.message }}</p>
            <form method="post">
              {% csrf_token %}
              <p>{{ reply_form.non_field_errors }}</p>
              <div class="form-group">
                <textarea name="message" id="message" rows="1" class="form-control"></textarea>
                {% if reply_form.message.errors %}
                    <div class="text-danger">
                      {{ reply_form.message.errors }}
                    </div>
                {% endif %}
                <input type="hidden" name="comment_id" value="{{ reply.id }}"></input>
                <button type="submit" name="reply" class="reply small" style="border: 0;"><i class="fas fa-reply fa-xs" aria-hidden="true"></i> Reply</button>
              </div>
            </form>
          
          </div>
  
          <!-- Display replies to the parent comment -->
          {% for reply in comment.get_replies %}
            <ul class="replies-list">
              <li class="comment">
                <div class="vcard">
                  <img src="{{ reply.author.profile_picture.url }}" alt="Image placeholder">
                </div>
                <div class="comment-body">
                  <h3>
                    <a href="{% url 'core:profile' reply.author.user.username %}">
                      {{ reply.author.user.username|title }}
                    </a>
                    <span class="small meta">- {{ reply.created_at }}</span>
                  </h3>
                  <p>{{ reply.message }}</p>
                  <form method="post">
                    {% csrf_token %}
                    <p>{{ reply_form.non_field_errors }}</p>
                    <div class="form-group">
                      <textarea name="message" id="message" rows="1" class="form-control"></textarea>
                      {% if reply_form.message.errors %}
                          <div class="text-danger">
                            {{ reply_form.message.errors }}
                          </div>
                      {% endif %}
                      <input type="hidden" name="comment_id" value="{{ reply.id }}"></input>
                      <button type="submit" name="reply" class="reply small" style="border: 0;"><i class="fas fa-reply fa-xs" aria-hidden="true"></i> Reply</button>
                    </div>
                  </form>
                 
                </div>
              </li>
            </ul>
          {% endfor %}
        </li>
      {% endif %}
    {% endfor %}
  </ul>
  

  <div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Leave a comment</h3>
    <form class="p-5 bg-light" method="post">
      <p>{{ comment_form.non_field_errors }}</p>
      {% csrf_token %}
      <div class="form-group">
        <label for="message">Message</label>
        <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>
        {% if comment_form.message.errors %}
            <div class="text-danger">
              {{ comment_form.message.errors }}
            </div>
        {% endif %}
      </div>
      <div class="form-group">
        <input type="submit" name="comment" value="Post Comment" class="btn btn-primary">
      </div>
    </form>
  </div>
</div>

templates/snippets/footer.html
<div class="site-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-4">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat reprehenderit magnam deleniti quasi
            saepe, consequatur atque sequi delectus dolore veritatis obcaecati quae, repellat eveniet omnis,
            voluptatem in. Soluta, eligendi, architecto.</p>
        </div>
        <div class="col-md-3 ml-auto">

          <ul class="list-unstyled float-left mr-5">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Advertise</a></li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Subscribes</a></li>
          </ul>
          <ul class="list-unstyled float-left">
            <li><a href="#">Travel</a></li>
            <li><a href="#">Lifestyle</a></li>
            <li><a href="#">Sports</a></li>
            <li><a href="#">Nature</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <div>
            <h3 class="footer-heading mb-4">Connect With Us</h3>
            <p>
              <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
              <a href="#"><span class="icon-twitter p-2"></span></a>
              <a href="#"><span class="icon-instagram p-2"></span></a>
              <a href="#"><span class="icon-rss p-2"></span></a>
              <a href="#"><span class="icon-envelope p-2"></span></a>
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center">
          <p>

            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
            with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com/"
              target="_blank">Colorlib</a>

          </p>
        </div>
      </div>
    </div>
  </div>

templates/snippets/navbar.html
<style>
  .search-form {
    display: flex;
    align-items: center;
  }

  .search-input {
    margin-right: 5px;
  }

  .search-button {
    white-space: nowrap;
  }
</style>
<div class="site-mobile-menu">
  <div class="site-mobile-menu-header">
    <div class="site-mobile-menu-close mt-3">
      <span class="icon-close2 js-menu-toggle"></span>
    </div>
  </div>
  <div class="site-mobile-menu-body"></div>
</div>

<header class="site-navbar" role="banner">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-4 site-logo">
        <a href="/" class="text-black h2 mb-0">Mini Blog</a>
      </div>
      <div class="col-8 text-right">
        <nav class="site-navigation" role="navigation">
          <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block mb-0">
            <li><a href="/">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url "core:post_create" %}">Create post</a></li>

            <li><a href="{% url 'core:settings' request.user.username %}">Settings</a></li>
            <li><a href="{% url 'core:logout' %}">Logout</a></li>
            {% endif %}
            <li class="search-li">
              <form action="{% url 'core:search' %}" method="GET" class="search-form text-black">
                <div class="form-inline">
                  <input type="text" class="form-control" name="query" placeholder="Search...">
                  <button type="submit" class="btn btn-primary"><span class="icon-search"></span>Search</button>
                </div>
              </form>
            </li>

            {% if user.is_authenticated %}

            <li class="dropdown">
              <a href="{% url 'core:profile' user.username %}" class="dropdown-toggle" data-toggle="dropdown">
                Logged in as: {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'core:profile' user.username %}">Profile</a>
                <a class="dropdown-item" href="/admin/">Admin Panel</a>
              </div>
            </li>

            {% else %}
            <li><a href="{% url 'core:login' %}">Login</a></li>
            <li><a href="{% url 'core:signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

templates/snippets/sidebar.html
<div class="sidebar-container">
  <div class="sidebar-box">
    <div class="bio text-center">
      <img src="{{ post.author.profile_picture.url }}" alt="Image Placeholder" class="img-fluid mb-5">
      <div class="bio-body">
        <h2>{{ post.author.user.username|title }}</h2>
        <p class="mb-4">{{ post.author.description|truncatechars:100 }}</p>
        <p><a href="{% url 'core:profile' post.author.user.username %}"
            class="btn btn-primary btn-sm rounded px-4 py-2">Read more</a></p>
        <p class="social">
          {% if post.author.facebook %}
          <a href="{{ post.author.facebook }}" class="p-2"><span class="fa fa-facebook"></span></a>
          {% endif %}
          {% if post.author.twitter %}
          <a href="{{ post.author.twitter }}" class="p-2"><span class="fa fa-twitter"></span></a>
          {% endif %}
          {% if post.author.instagram %}
          <a href="{{ post.author.instagram }}" class="p-2"><span class="fa fa-instagram"></span></a>
          {% endif %}
          {% if post.author.youtube %}
          <a href="{{ post.author.youtube }}" class="p-2"><span class="fa fa-youtube-play"></span></a>
          {% endif %}
        </p>
      </div>
    </div>

    <h3 class="heading">Popular Posts</h3>
    <div class="post-entry-sidebar">
      <ul>
        {% for popular_post in popular_posts %}
        <li>
          <a href="{% url 'core:post_detail' popular_post.slug %}">
            <img src="{{ popular_post.image.url }}" alt="Image placeholder" class="mr-4">
            <div class="text">
              <h4>{{ popular_post.title }}</h4>
              <div class="post-meta">
                <span class="mr-2">{{ popular_post.created_at|date:"M d, Y" }}</span>
              </div>
            </div>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>

    <div class="sidebar-box">
      <h3 class="heading">Categories</h3>
      <ul class="categories">
        {% for category in categories %}
        <li><a href="{% url 'core:category-posts' category.name %}">{{ category.name }} <span>({{ category.post_count}})</span></a></li>
        {% endfor %}


      </ul>

      <h3 class="heading">Tags</h3>
      <ul class="tags">
        {% for tag in tags %}

        <li><a href="{% url 'core:tag-posts' tag.name %}">{{ tag.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>