blogging/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import *


app_name = "core"

urlpatterns = [
    path('', homepage, name="homepage"),
    path('signup/', register_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='reset_password'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # posts
    path('post/create/', post_create_view, name='post_create'),
    path('post/<slug:slug>/edit/', post_edit, name='post_edit'),
    path('post/<slug:slug>/delete/', post_delete, name='post_delete'),
    path('post/<slug:slug>/', post_detail, name='post_detail'),
    path('category/<str:category_slug>/', category_posts, name='category-posts'),
    path('tag/<str:tag_slug>/', tag_posts, name='tag-posts'),

    #user
    path('user/@<str:username>/', profile_view, name='profile'),
    path('user/@<str:username>/edit/', settings, name='settings'),
    path('search/', search, name='search'),

]

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse
from autoslug import AutoSlugField
from taggit.managers import TaggableManager


def create_author(sender, instance, created, **kwargs):
    if created:
        Author.objects.create(user=instance)


post_save.connect(create_author, sender=User)


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        upload_to='author_profile_pictures', default="author_profile_pictures/81IBlQyTj3L._AC_SX425_.jpg")
    description = models.TextField()
    facebook = models.URLField()
    twitter = models.URLField()
    instagram = models.URLField()
    youtube = models.URLField()

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    slug = AutoSlugField(unique=True, populate_from='title')
    created_at = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Comment by {self.author.user.username} on {self.post.title}"

    def get_author_profile_url(self):
        return reverse('core:profile', args=[self.author.user.username])

    def get_replies(self):
        return Comment.objects.filter(parent=self, parent__isnull=False).order_by('created_at')

    @property
    def children(self):
        descendants = []
        for reply in self.replies.all():
            descendants.append(reply)
            descendants.extend(reply.children)
        return descendants

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

templates/category_posts.html
{% extends "base.html" %}
{% load custom_filters %}

{% block styling %}
.post-content-body {
  margin-top: 30px;
}

.post-content-body img {
  width: 100%;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.post-details {
  margin-top: 20px;
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 10px;
}

.post-meta {
  margin-bottom: 10px;
}

.post-category {
  margin-right: 10px;
  padding: 8px 16px;
  font-size: 14px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 50px;
  transition: background-color 0.3s ease;
}

.post-category:hover {
  background-color: #0056b3;
}

.post-content {
  margin-top: 30px;
  font-size: 18px;
  line-height: 1.8;
  color: #444;
}

.post-content p {
  margin-bottom: 20px;
}

.post-content a {
  color: #007bff;
  text-decoration: none;
  transition: color 0.3s ease;
}

.post-content a:hover {
  color: #0056b3;
}

.post-content blockquote {
  margin: 30px 0;
  padding: 20px;
  border-left: 5px solid #007bff;
  background-color: #f9f9f9;
}

.post-content blockquote p {
  margin-bottom: 0;
}

.post-content pre {
  margin: 30px 0;
  padding: 20px;
  background-color: #f9f9f9;
  color: #444;
  overflow-x: auto;
  font-family: monospace;
}

.post-content pre code {
  display: block;
  white-space: pre;
}

.main-image {
  width: 100%;
  height: auto;
  max-height: 400px;
}

.sub-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
{% endblock styling %}

{% block content %}

<div class="site-section bg-white">
  <div class="container">
    <h1 class="mb-5">Posts in {{ category.name }} category</h1>
    <div class="row mt-5">
      {% for post in posts %}
      <div class="col-lg-4 mb-4">
        <div class="entry1">
          <a href="{% url 'core:post_detail' post.slug %}"><img src="{{ post.image.url }}" alt="Image" class="img-fluid rounded img-post"></a>
          <div class="excerpt">
            <span class="post-category text-white {{ random_button_class }} mb-3">{{ category.name}}</span>
            <h2><a href="{% url 'core:post_detail' post.slug %}">{{ post.title|truncatechars:50 }}</a></h2>
            <div class="post-meta align-items-center text-left clearfix">
              <figure class="author-figure mb-0 mr-3 float-left"><img src="{{ post.author.profile_picture.url }}" alt="Image" class="img-fluid"></figure>
              <span class="d-inline-block mt-1">By <a href="{% url "core:profile" post.author.user.username %}">{{ post.author.user.username|title }}</a></span>
              <span>&nbsp;-&nbsp; {{ post.created_at }}</span>
            </div>
            <p>{{ post.content|truncatechars:200 }}</p>
            <p><a href="{% url 'core:post_detail' post.slug %}">Read More</a></p>
            {% if user.is_authenticated and user == post.author.user or user.is_superuser %}
            <div class="d-flex justify-content-between">
              <a href="{% url 'core:post_edit' post.slug %}" class="btn btn-primary">Edit</a>
              <form action="{% url 'core:post_delete' post.slug %}" method="post" class="d-inline">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    
  </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block styling %}
.img-post {
height: 350px;
}

<!-- .custom-pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 20px;
}

.custom-pagination a,
.custom-pagination span {
  display: inline-block;
  margin: 0 5px;
  color: #fff;
  background-color: #333;
  padding: 5px 10px;
  border-radius: 3px;
  text-align: center;
  line-height: 1;
  text-decoration: none;
}

.custom-pagination a:hover {
  background-color: #555;
}

.custom-pagination .active {
  background-color: #555;
} -->

.no-posts {
text-align: center;
padding: 20px;
}

.no-posts h2 {
font-size: 24px;
}

.no-posts p {
font-size: 16px;
}

@media (max-width: 768px) {
.no-posts {
padding: 10px;
}

.no-posts h2 {
font-size: 24px;
}

.no-posts p {
font-size: 16px;
}
}
{% endblock styling %}

{% block content %}
<div class="site-section bg-light">
  <div class="container">
    <div class="row align-items-stretch retro-layout-2">
      <div class="col-md-4">
        {% for post in posts|slice:":2" %}
        <a href="{% url 'core:post_detail' post.slug %}" class="h-entry mb-30 v-height gradient"
          style="background-image: url('{{ post.image.url }}');">
          <div class="text">
            <div class="post-categories mb-3">
              <span class="post-category {{ random_button_class }}">{{ post.category }}</span>
            </div>
            <h2>{{ post.title|truncatechars:40 }}</h2>
            <span class="date">{{ post.created_at }}</span>
          </div>
        </a>
        {% empty %}
        <div class="no-posts">
          <h2>No posts available</h2>
          <p>Check back later for updates.</p>
        </div>
        {% endfor %}
      </div>
      <div class="col-md-4">
        {% for post in posts|slice:"2:3" %}
        <a href="{% url 'core:post_detail' post.slug %}" class="h-entry img-5 h-100 gradient"
          style="background-image: url('{{ post.image.url }}');">
          <div class="text">
            <div class="post-categories mb-3">
              <span class="post-category {{ random_button_class }}">{{ post.category }}</span>
            </div>
            <h2>{{ post.title|truncatechars:40 }}</h2>
            <span class="date">{{ post.date }}</span>
          </div>
        </a>
        {% empty %}
        <div class="no-posts">
          <h2>No posts available</h2>
          <p>Check back later for updates.</p>
        </div>
        {% endfor %}
      </div>
      <div class="col-md-4">
        {% for post in posts|slice:"3:5" %}
        <a href="{% url 'core:post_detail' post.slug %}" class="h-entry mb-30 v-height gradient"
          style="background-image: url('{{ post.image.url }}');">
          <div class="text">
            <div class="post-categories mb-3">
              <span class="post-category {{ random_button_class }}">{{ post.category }}</span>
            </div>
            <h2>{{ post.title|truncatechars:40 }}</h2>
            <span class="date">{{ post.created_at }}</span>
          </div>
        </a>
        {% empty %}
        <div class="no-posts">
          <h2>No posts available</h2>
          <p>Check back later for updates.</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12 text-center">
        <h2>Recent Posts</h2>
        {% if user.is_authenticated and user == post.author.user or user.is_superuser %}
        <div class="mt-5">
          <a href="{% url 'core:post_create' %}" class="btn btn-primary">Create Post</a>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="row">
      {% if posts %}
      {% for post in posts|slice:":6" %}
      <div class="col-lg-4 mb-4">
        <div class="entry1">
          <a href="{% url 'core:post_detail' post.slug %}">
            <img src="{{ post.image.url }}" alt="Image" class="img-fluid rounded img-post">
          </a>
          <div class="excerpt">
            <span class="post-category text-white bg-secondary mb-3">{{ post.category }}</span>
            <h2><a href="{% url 'core:post_detail' post.slug %}">{{ post.title|truncatechars:50 }}</a></h2>
            <div class="post-meta align-items-center text-left clearfix">
              <figure class="author-figure mb-0 mr-3 float-left">
                <img src="{{ post.author.profile_picture.url }}" alt="Image" class="img-fluid">
              </figure>
              <span class="d-inline-block mt-1">By <a href="{% url 'core:profile' post.author.user.username %}">{{ post.author.user.username|title }}</a></span>
              <span>&nbsp;-&nbsp;{{ post.created_at|date:"F d, Y"|title }}</span>
            </div>
            <p>{{ post.content|truncatechars:100 }}</p>
            <p><a href="{% url 'core:post_detail' post.slug %}">Read More</a></p>
            {% if user.is_authenticated and user == post.author.user or user.is_superuser %}

            <div class="d-flex justify-content-between">
              <a href="{% url 'core:post_edit' post.slug %}" class="btn btn-primary">Edit</a>
              <form action="{% url 'core:post_delete' post.slug %}" method="post" class="d-inline">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
            {% endif %}

          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="no-posts col-md-12">
        <div class="text-center">
          <h2>No posts available</h2>
          <p>Check back later for updates.</p>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  <div class="row text-center pt-5 border-top">
    <div class="col-md-12">
      {% if posts.has_other_pages %}
      <div class="pagination">
        {% if posts.has_previous %}
        <a href="{% url 'core:homepage' %}" class="page-link">&laquo; First</a>
        <a href="?page={{ posts.previous_page_number }}" class="page-link">&lsaquo; Previous</a>
        {% endif %}

        {% for page in posts.paginator.page_range %}
        {% if page == posts.number %}
        <a href="?page={{ page }}" class="page-link active">{{ page }}</a>
        {% else %}
        <a href="?page={{ page }}" class="page-link">{{ page }}</a>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}" class="page-link">Next &rsaquo;</a>
        <a href="?page={{ posts.paginator.num_pages }}" class="page-link">Last &raquo;</a>
        {% endif %}
      </div>
      {% endif %}



    </div>
  </div>
</div>
</div>
</div>


{% endblock %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card mt-5">
        <div class="card-body">
          <h2 class="card-title">Delete Post</h2>
          <p class="card-text">Are you sure you want to delete this post?</p>
          <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <button type="button" class="btn btn-secondary" onclick="goBack()">Cancel</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function goBack() {
    window.history.back();
  }
</script>

{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}

<div class="site-section bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-5">
        <div class="subscribe-1">
          <h2>Edit Post</h2>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.title.id_for_label }}">Title:</label>
              <input type="text" class="form-control" name="title" maxlength="200" required=""id="id_title" value="{{ form.title.value|default_if_none:'' }}">
              {% if form.title.errors %}
                <small class="text-danger">{{ form.title.errors }}</small>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="{{ form.content.id_for_label }}">Content:</label>
              <textarea id="id_content" name="content" class="form-control" rows="6" value="{{ form.content.value|default_if_none:'' }}">{{ form.content.value|default_if_none:'' }}</textarea>
              {% if form.content.errors %}
                <small class="text-danger">{{ form.content.errors }}</small>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="{{ form.category.id_for_label }}">Category:</label>
              {{ form.category }}
              {% if form.category.errors %}
                <small class="text-danger">{{ form.category.errors }}</small>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="{{ form.tags.id_for_label }}">Tags:</label>
              <input type="text" class="form-control" name="tags" value="{% for value in form.tags.value %}{{ value }} {% endfor %}" id="{{ form.tags.id_for_label }}">
              {% if form.tags.errors %}
              <small class="text-danger">{{ form.tags.errors }}</small>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="{{ form.image.id_for_label }}">Image:</label>
              <input type="file" name="image" id="id_image" accept="image/*">
              {% if form.image.errors %}
                <small class="text-danger">{{ form.image.errors }}</small>
              {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'core:post_detail' post.slug %}" class="btn btn-secondary">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<style>
    .img-post {
        height: 350px;
    }

    /* .custom-pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 20px;
}

.custom-pagination a,
.custom-pagination span {
  display: inline-block;
  margin: 0 5px;
  color: #fff;
  background-color: #333;
  padding: 5px 10px;
  border-radius: 3px;
  text-align: center;
  line-height: 1;
  text-decoration: none;
}

.custom-pagination a:hover {
  background-color: #555;
}

.custom-pagination .active {
  background-color: #555;
} */

    .no-posts {
        text-align: center;
        padding: 20px;
    }

    .no-posts h2 {
        font-size: 24px;
    }

    .no-posts p {
        font-size: 16px;
    }

    @media (max-width: 768px) {
        .no-posts {
            padding: 10px;
        }

        .no-posts h2 {
            font-size: 24px;
        }

        .no-posts p {
            font-size: 16px;
        }
    }
</style>
<div class="container">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-6 col-lg-4 mb-5">
            <div class="blog-entry">
                <a href="{% url 'core:post_detail' post.slug %}" class="img-link">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                </a>
                <div class="text p-4">
                    <h3 class="heading"><a href="{% url 'core:post_detail' post.slug %}">{{ post.title }}</a></h3>
                    <p>{{ post.content }}</p>
                    <div class="meta">
                        <a href="{% url 'core:post_detail' post.slug %}" class="mr-2">{{ post.created_at|date:"F d, Y"}}</a>
                        <a href="{% url 'core:post_detail' post.slug %}" class="meta-chat"><spanclass="icon-chat"></span> {{ post.comments.count }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row text-center pt-5 border-top">
        <div class="col-md-12">
            {% if posts.has_other_pages %}
            <div class="pagination">
                {% if posts.has_previous %}
                <a href="{% url 'core:homepage' %}" class="page-link">&laquo; First</a>
                <a href="?page={{ posts.previous_page_number }}" class="page-link">&lsaquo; Previous</a>
                {% endif %}

                {% for page in posts.paginator.page_range %}
                {% if page == posts.number %}
                <a href="?page={{ page }}" class="page-link active">{{ page }}</a>
                {% else %}
                <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                {% endif %}
                {% endfor %}

                {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="page-link">Next &rsaquo;</a>
                <a href="?page={{ posts.paginator.num_pages }}" class="page-link">Last &raquo;</a>
                {% endif %}
            </div>
            {% endif %}



        </div>
    </div>
</div>
{% endblock %}

templates/search_results.html
{% extends "base.html" %}

{% block content %}
  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="mb-4">Search Results for "{{ query }}"</h2>
          {% if posts %}
            <div class="row">
              {% for post in posts %}
                <div class="col-md-6 col-lg-4 mb-5">
                  <div class="blog-entry">
                    <a href="{% url 'core:post_detail' post.slug %}" class="img-link">
                      <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                    </a>
                    <div class="text p-4">
                      <h3 class="heading"><a href="{% url 'core:post_detail' post.slug %}">{{ post.title }}</a></h3>
                      <p>{{ post.content }}</p>
                      <div class="meta">
                        <a href="{% url 'core:post_detail' post.slug %}" class="mr-2">{{ post.created_at|date:"F d, Y" }}</a>
                        <a href="{% url 'core:post_detail' post.slug %}" class="meta-chat"><span class="icon-chat"></span> {{ post.comments.count }}</a>
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          {% else %}
            <p>No results found.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/single.html
{% extends "base.html" %}

{% block styling %}
.post-content-body {
margin-top: 30px;
}

.post-content-body img {
width: 100%;
border-radius: 10px;
box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.post-details {
margin-top: 20px;
background-color: #f9f9f9;
padding: 20px;
border-radius: 10px;
}

.post-meta {
margin-bottom: 10px;
}
.post-category {
margin-right: 10px;
padding: 8px 16px;
font-size: 14px;
background-color: #007bff;
color: #fff;
border: none;
border-radius: 50px;
transition: background-color 0.3s ease;
}

.post-category:hover {
background-color: #0056b3;
}

.post-content {
margin-top: 30px;
font-size: 18px;
line-height: 1.8;
color: #444;
}

.post-content p {
margin-bottom: 20px;
}

.post-content a {
color: #007bff;
text-decoration: none;
transition: color 0.3s ease;
}

.post-content a:hover {
color: #0056b3;
}

.post-content blockquote {
margin: 30px 0;
padding: 20px;
border-left: 5px solid #007bff;
background-color: #f9f9f9;
}

.post-content blockquote p {
margin-bottom: 0;
}

.post-content pre {
margin: 30px 0;
padding: 20px;
background-color: #f9f9f9;
color: #444;
overflow-x: auto;
font-family: monospace;
}

.post-content pre code {
display: block;
white-space: pre;
}
.main-image {
width: 100%;
height: auto;
max-height: 400px;
}

.sub-image {
width: 100%;
height: 100%;
object-fit: cover;
}



{% endblock styling %}

{% block content %}
<div class="site-cover site-cover-sm same-height overlay single-page"
  style="background-image: url('{{ post.image.url }}');">
  <div class="container">
    <div class="row same-height justify-content-center">
      <div class="col-md-12 col-lg-10">
        <div class="post-entry text-center">
          <span class="post-category text-white bg-success mb-3">{{ post.category.name }}</span>

          <h1 class="mb-4"><a href="#">{{ post.title }}</a></h1>
          <div class="post-meta align-items-center text-center">
            <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="{{ post.author.profile_picture.url }}"
                alt="Image" class="img-fluid"></figure>
            <span class="d-inline-block mt-1">By {{ post.author.user.username|title }}</span>
            <span>&nbsp;-&nbsp; {{ post.created_at|date:"F d, Y" }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="site-section py-lg">
  <div class="container">
    <div class="row blog-entries element-animate">
      <div class="col-md-12 col-lg-8 main-content">
        <div class="post-actions">
          {% if request.user.author == post.author %}
            <a href="{% url 'core:post_edit' post.slug %}" class="btn btn-primary btn-sm">Edit</a>
            <a href="{% url 'core:post_delete' post.slug %}" class="btn btn-danger btn-sm">Delete</a>
          {% endif %}
        </div>
        <div class="post-content-body">
          <div class="post-details">
            <p class="post-content">{{ post.content }}</p>
            <div class="post-tags">
              <h5>Tags:</h5>
              <div class="tags-list">
                {% for tag in post.tags.all %}
                <button class="btn btn-secondary"><a href="{% url "core:tag-posts" tag.name %}">{{ tag.name }}</a></button>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        {% include "snippets/comments.html" %}
      </div>

      <div class="col-md-12 col-lg-4 sidebar">
        <div class="sidebar-box search-form-wrap">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
            </div>
          </form>
        </div>
        {% include "snippets/sidebar.html" %}
      </div>
    </div>
  </div>
</section>



{% endblock %}

templates/tag_posts.html
{% extends "base.html" %}

{% block styling %}
.post-content-body {
  margin-top: 30px;
}

.post-content-body img {
  width: 100%;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.post-details {
  margin-top: 20px;
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 10px;
}

.post-meta {
  margin-bottom: 10px;
}

.post-category {
  margin-right: 10px;
  padding: 8px 16px;
  font-size: 14px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 50px;
  transition: background-color 0.3s ease;
}

.post-category:hover {
  background-color: #0056b3;
}

.post-content {
  margin-top: 30px;
  font-size: 18px;
  line-height: 1.8;
  color: #444;
}

.post-content p {
  margin-bottom: 20px;
}

.post-content a {
  color: #007bff;
  text-decoration: none;
  transition: color 0.3s ease;
}

.post-content a:hover {
  color: #0056b3;
}

.post-content blockquote {
  margin: 30px 0;
  padding: 20px;
  border-left: 5px solid #007bff;
  background-color: #f9f9f9;
}

.post-content blockquote p {
  margin-bottom: 0;
}

.post-content pre {
  margin: 30px 0;
  padding: 20px;
  background-color: #f9f9f9;
  color: #444;
  overflow-x: auto;
  font-family: monospace;
}

.post-content pre code {
  display: block;
  white-space: pre;
}

.main-image {
  width: 100%;
  height: auto;
  max-height: 400px;
}

.sub-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
{% endblock styling %}

{% block content %}

<div class="site-section bg-white">
  <div class="container">
    <h1 class="mb-5">Posts in {{ tag.name }} tag</h1>
    <div class="row mt-5">
      {% for post in posts %}
      <div class="col-lg-4 mb-4">
        <div class="entry1">
          <a href="{% url 'core:post_detail' post.slug %}"><img src="{{ post.image.url }}" alt="Image" class="img-fluid rounded img-post"></a>
          <div class="excerpt">
            <h2><a href="{% url 'core:post_detail' post.slug %}">{{ post.title|truncatechars:50 }}</a></h2>
            <div class="post-meta align-items-center text-left clearfix">
              <figure class="author-figure mb-0 mr-3 float-left"><img src="{{ post.author.profile_picture.url }}" alt="Image" class="img-fluid"></figure>
              <span class="d-inline-block mt-1">By <a href="{% url "core:profile" post.author.user.username %}">{{ post.author.user.username|title }}</a></span>
              <span>&nbsp;-&nbsp; {{ post.created_at }}</span>
            </div>
            <p>{{ post.content|truncatechars:200 }}</p>
            <p><a href="{% url 'core:post_detail' post.slug %}">Read More</a></p>
            {% if user.is_authenticated and user == post.author.user or user.is_superuser %}
            <div class="d-flex justify-content-between">
              <a href="{% url 'core:post_edit' post.slug %}" class="btn btn-primary">Edit</a>
              <form action="{% url 'core:post_delete' post.slug %}" method="post" class="d-inline">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    
  </div>
</div>
{% endblock %}